[package]
name = "aoc2020-day2"
version = "0.1.0"
authors = ["Jess Martin <jessmartin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
